name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: buildprod.sh
        run: ./scripts/buildprod.sh

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.2

      - name: Deploy
        run: gcloud builds submit --tag australia-southeast2-docker.pkg.dev/notely-449312/notely-ar-repo/notely:latest
